### ISSUE TITLE
Проверка ДЗ1 СУБД

### ISSUE THREAD

**Issue by 3kybika** [go-park-mail-ru/2024_2_SaraFun#13]
- [x]  1. Мэтч, лайк и дизлайк кажутся поводами для аномалий:
- Я же верно понимаю, что мэтч - это наличие 2х взаимных лайков? Т.е. мы можем достать всё это из таблицы с лайками?
- Также кажется разделение на лайк и дизлайк создает возможность для аномалии - можно поставить и лайк и дизлайк, и контролировать это придется со стороны приложения? Еще и метч можно получить...Да, все это можно обойти констрейнами - но зачем, если можно изначально обойтись только табличкой лайка с полем bool? Или нам дата нужна, чтобы смотреть какая запись позже появилось - лайк или дизлайк.
- [x] 2. Сессиии пользователей - а где они?
- [x] 3. А что с функционалом подарков? Где они как сущности? Я вижу есть упоминание в тарифов
- [x] 4.У пользователя есть баланс. Кажется, у нас в системе есть транзакции с денежными переводами и прочее, но в БД мы их не храним?
- [x] 5. В табличке Message имеется поле status: text - может имеет смысл его сделать Enum?
- [x] 6. Password же не хранится в виде чистого текста? Лучше хэшом ли хэшом с солью или каким-то иным способом. Тогда утечка БД будет не столь страшна. И соответственно его надо будет назвать password_hash или как-то иначе.
- [x] 7. Хотелось бы увидеть все функциональные зависимости, а не только от первичного ключа. Например:
В табличке User указана ФЗ `{id} -> username, email, password, profile, balance`, однако у нас скорее всего существуют и другие ФЗ, например от потенциальных ключей: `{username} -> id, email, password, profile, balance` - ведь username должен быть уникальным и т.п. Это все надо будет в constraints указать. Кстати, такие альтернативные ключи было бы здорово пометить как-то: AK, PK и FK - пометки, которые хотелось бы видеть, FK - есть, а остальных - нет.
- [x] 8. Как-то на лекции мы говорили о техничеких полях:
https://3kybika.github.io/technopark-dbms-lectures/04/#62
Давайте добавим! Может не везде оно имеет смысл с точки зрения бизнеса, но аналитики будут благодарны  при разоре инцидентов :)
- [x] И последнее: выделенные функциональные зависимости подсказывают какие еще ограничения целостности нам надо наложить на нашу схему.

**Comment by KranjQ** [comment]
1. Таблицы убрали, добавили таблицу reaction, где хранится лайк/дизлайк
2. Сессии планируем хранить в redis, поэтому для них таблицу не делали
3. Функционал подарков не обязателен, мы решили его убрать. Также мы пересмотрели подписку, теперь у нас только одна подписка, поэтому таблицу тарифов мы убрали
4. Создали таблицу для платежный операций
5. Поле status теперь enum
6. Пароль у нас в базе данных хранится в хэшированном виде, название поля поменяли на password_hash
7. Добавили фз и AK
8. Добавили техническое поле created_at во всех таблицах

**Comment by 3kybika** [comment]
Здорово! Но...
4. Про баланс  - а пополнения будем отслеживать?
7. А вот и не все :)  User: {email} -> username, password_hash, profile; Reaction: {author, receiver} -> id, type
8. И еще updated_at

**Comment by KranjQ** [comment]
4. Пополнения будут отслеживаться в таблице Purchase.
7. Добавили
8. Добавили

**Comment by 3kybika** [comment]
Почти всё!
А теперь нам функциональные зависимости подскажут, какие еще constraints нам надо наложить
